// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK_rXjJpqC8J00n2AeEcTs6_PJuKDMvR4',
    appId: '1:83415966587:web:313cc69d910a702a6bd3de',
    messagingSenderId: '83415966587',
    projectId: 'superheromoods-cit',
    authDomain: 'superheromoods-cit.firebaseapp.com',
    storageBucket: 'superheromoods-cit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdloFrHQXRfUJwjKIfZC25Uu7mD0OJ9Ck',
    appId: '1:83415966587:android:a5f88a26ee4fd8586bd3de',
    messagingSenderId: '83415966587',
    projectId: 'superheromoods-cit',
    storageBucket: 'superheromoods-cit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzIfX5N6XkTsYOqgvj-WVZpynWTUFPkeA',
    appId: '1:83415966587:ios:18d55dad3972a69d6bd3de',
    messagingSenderId: '83415966587',
    projectId: 'superheromoods-cit',
    storageBucket: 'superheromoods-cit.appspot.com',
    iosBundleId: 'com.example.superheromood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzIfX5N6XkTsYOqgvj-WVZpynWTUFPkeA',
    appId: '1:83415966587:ios:18d55dad3972a69d6bd3de',
    messagingSenderId: '83415966587',
    projectId: 'superheromoods-cit',
    storageBucket: 'superheromoods-cit.appspot.com',
    iosBundleId: 'com.example.superheromood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK_rXjJpqC8J00n2AeEcTs6_PJuKDMvR4',
    appId: '1:83415966587:web:b45d6eb2c352ace26bd3de',
    messagingSenderId: '83415966587',
    projectId: 'superheromoods-cit',
    authDomain: 'superheromoods-cit.firebaseapp.com',
    storageBucket: 'superheromoods-cit.appspot.com',
  );
}
